POST http://localhost:9999/auth
Content-Type: application/json

{
  "email": "vigi.nat@gmail.com",
  "password": "password"
}

###

POST http://localhost:9999/auth/register
Content-Type: application/json

{
  "email": "vigi.nat@gmail.com",
  "password": "password"
}

