GET http://localhost:9999/movies

###

GET http://localhost:9999/movies/594c4c0370c103b4684b99c8

###

GET http://localhost:9999/movies/DOES_NOT_EXIST

###

POST http://localhost:9999/movies
Content-Type: application/json

{
  "title": "Antman",
  "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo aperiam sint, modi eligendi veniam maiores recusandae ad suscipit!                    Temporibus saepe officia laboriosam, ducimus voluptatibus vel placeat dolor ipsum illo quo. Voluptatibus quas mollitia explicabo                     veniam, repellendus quo ducimus magnam dignissimos ut sunt perferendis? Aliquid rem illum tempore! Sunt, minus adipisci.",
  "yearReleased": 2015
}


###

PUT http://localhost:9999/movies/594c5b7c4e18cfba4584586d
Content-Type: application/json

{
  "title": "Superman",
  "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo aperiam sint, modi eligendi veniam maiores recusandae ad suscipit!Temporibus saepe officia laboriosam, ducimus voluptatibus vel placeat dolor ipsum illo quo. Voluptatibus quas mollitia explicabo veniam, repellendus quo ducimus magnam dignissimos ut sunt perferendis? Aliquid rem illum tempore! Sunt, minus adipisci.",
  "yearReleased": 2012,
  "cast": [{
    "person": "594cadacee5e15e22effbba3",
    "role": "Boo Bah"
  }],
  "writers": [{
    "person": "594e2bcab121850e79c51cdc",
    "role": "cra cra"
  }]
}

###

DELETE http://localhost:9999/movies/594da999cd4f7f04f26b2e86


